version: '3.7'
services:
  webserver:
    image: apache/airflow:1.10.14
    # build:
    #   context: .
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    environment:
      - PYTHONPATH=/opt/airflow
    env_file:
      .env  
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command:
      ["webserver"]
  scheduler:
    image: apache/airflow:1.10.14
    # build:
    #   context: .
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - webserver
    environment:
      - PYTHONPATH=/opt/airflow
    env_file:
      .env  
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: ["scheduler"]

