version: '3.7'
networks:
  airflow:

services:
  webserver:
    image: apache/airflow:1.10.14
    # build:
    #   context: .
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    depends_on:
      - initdb
    environment:
      - PYTHONPATH=/opt/airflow
    env_file:
      .env  
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command:
      ["webserver"]
    networks:
      - airflow
  scheduler:
    image: apache/airflow:1.10.14
    # build:
    #   context: .
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - webserver
    environment:
      - PYTHONPATH=/opt/airflow
    env_file:
      .env  
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: ["scheduler"]
    networks:
      - airflow
  initdb:
    image: apache/airflow:1.10.14
    env_file:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    entrypoint: /bin/bash
    deploy:
      restart_policy:
        condition: on-failure
        delay: 8s
        max_attempts: 5
    command: -c "airflow db init"
    networks:
      - airflow

