version: '3.7'
networks:
  airflow:

services:
  webserver:
    build:
      context: .
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8080:8080"
    depends_on:
      - initdb
    environment:
      - PYTHONPATH=/opt/airflow
    env_file:
      .env  
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command:
      ["webserver"]
    networks:
      - airflow
  scheduler:
    build:
      context: .
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./scripts:/opt/airflow/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - webserver
    environment:
      - PYTHONPATH=/opt/airflow
    env_file:
      .env  
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: ["scheduler"]
    networks:
      - airflow
  flower:
    build:
      context: .
    ports:
      - 5555:5555
    volumes:
      - ./airflow/logs:/opt/airflow/logs
    environment:
      - PYTHONPATH=/opt/airflow
    env_file:
      - .env  
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    command: flower
    networks:
      - airflow
  worker:
    build:
      context: .
    environment:
      - PYTHONPATH=/opt/airflow
    env_file:
      - .env
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - /var/run/docker.sock:/var/run/docker.sock
    command: worker
    depends_on:
      - scheduler
  initdb:
    build:
      context: .
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./airflow/logs:/opt/airflow/logs
      - ./airflow/entrypoint.sh:/opt/airflow/entrypoint.sh
      - ./scripts:/opt/airflow/scripts
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - PYTHONPATH=/opt/airflow
    env_file:
      - .env  
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    entrypoint: /opt/airflow/entrypoint.sh
    networks:
      - airflow

